### ISSUE TITLE
Orange Pi Zero support

### ISSUE THREAD

**Issue by bachoo786** [googlesamples/assistant-sdk-python#363] opened 2019-07-19 09:55 UTC
Hello all

I have managed to install google assistant on orange pi zero and can communicate with the assistant using the pushtotalk.py file. However I wanted to use the "googlesamples-assistant-hotword" but it gives me an error saying Segmentation Fault.

Can someone please help with that? Has anyone installed google assistant on Orange Pi Zero?

Thanks.

**Comment by shivasiddharth** [comment] 2019-07-19 10:01
Duplicate of #356

**Comment by Fleker** [comment] 2019-07-19 14:31
Duplicate, closing.

**Closed by Fleker** 2019-07-19 14:31 UTC

**Comment by bachoo786** [comment] 2019-07-19 14:40
Duplicate of 356? How?
