### ISSUE TITLE
textinputy.py is doing weird things

### ISSUE THREAD

**Issue by Simonx22** [googlesamples/assistant-sdk-python#144] opened 2017-12-22 12:21 UTC
Hello, after I've tried textinput.py I've noticed that it's doing weird things. It's either not answering my questions at all or is talking about things that don't make sense. Here is an example:

> you: give me a trivia question
assistant: None
you: play lucky trivia
assistant: None
you: set an alarm
assistant: None
you: what's the weather?
assistant: None
you: hello in german
assistant: None
you: how are you
assistant: None
you: facebook stock price
assistant: None

or

> you: how are you doing
assistant: It was created in 1966 by Dr. Maulana Karenga, a professor of African Studies

**Comment by Fleker** [comment] 2017-12-22 18:32
Can you try with the `pushtotalk.py` sample, giving the same queries and see if you get the same thing? It may also give you some audio out which could provide more information.

I'll try to reproduce on my end.

**Comment by Fleker** [comment] 2017-12-22 18:45
I reproduced your case in the SDK as well as on my phone. It looks like there's a bug in getting the supplemental display text of the question. However, you are still in the Trivia Question flow so your other prompts get ignored.

**Phone**
Me: give me a trivia question
Assistant: I like this one. It's a science question. How many teaspoons are in one tablespoon? 3, 2.5, or 6?
Me: play lucky trivia
Assistant: Sorry. How many teaspoons are in one tablespoon? 3, 2.5, or 6?
Me: set an alarm
Assistant: Once again, please. How many teaspoons are in one tablespoon? 3, 2.5, or 6?
Me: what's the weather?
Assistant: Sorry, we'll have to move on.
Assistant: I wish you had said 3. Would you like another question?
Me: hello in German
Assistant: Sorry, . Would you like another question?
Me: how are you
Assistant: Try saying just "yes" or "no". Would you like another question?
Me: Facebook stock price
Assistant: Let's just call it a game. Alright. Thanks for playing.
Me: how are you doing?
Assistant: I'm feeling pretty chill, since the weather is cooling down in many parts of the country :snowman: 
Assistant: It's a good time to stay warm indoors and dig up some fun winter facts
Assistant: I learned that the record for the largest snowflake is 15 inches (38.1 cm) wide and 8 inches (20.32 cm) thick :snowflake: 

So it looks like a few problems are happening here:

* Saying "Give me a trivia question" puts you into a conversational flow that you may not realize
* No `supplemental_display_text` is available in this flow
* Your later requests are being made within this context, causing them to go back to that same issue
* "How are you doing" returns a lot of text, in three separate text bubbles. However, `supplemental_display_text` only returns the last one, so you do not get the full context of why this was being stated.

I'm going to raise these issues. Thanks for filing this issue.

**Comment by Fleker** [comment] 2018-05-02 22:26
Closing as part of #158 and #238

**Closed by Fleker** 2018-05-02 22:26 UTC
