### ISSUE TITLE
Include Assistant response in library

### ISSUE THREAD

**Issue by Starlon87** [googlesamples/assistant-sdk-python#227] opened 2018-04-10 02:49 UTC
We want to develop a demo, similar to the dialogue scenes, need to display the user's request and assistant's respond to the content, as well as the interactive state(idle,listening,speaking,etc.)

but found the library don't provide the texts of assistant's response, 
the service provide response texts, but no interactive state.

How can we get both response texts & interactive state?

Tks.

**Comment by Fleker** [comment] 2018-04-10 17:18
Right now that's not a feature that is available in the library. I'll mark this as an enhancement.

**Comment by Starlon87** [comment] 2018-04-11 01:06
@Fleker   Thanks.
Could you tell us  how to get the interactive state(idle,listening,speaking,etc.) by Service SDK?
or Service SDK not support this feature yet?

**Comment by Fleker** [comment] 2018-04-11 17:28
The current state is not something that can be queried, but it is something that can be tracked in the client by changing the state during different parts of the application. When you are streaming audio, it is 'listening' and when you get responses back it is 'speaking'.

**Comment by Fleker** [comment] 2018-05-02 21:58
Duplicate of #216

**Closed by Fleker** 2018-05-02 21:58 UTC
Labels: duplicate, enhancement, library

**Comment by checkomkar** [comment] 2018-11-27 20:18
How to use event output of ON_RENDER_RESPONSE to display text in a webpage?
