### ISSUE TITLE
Google Assistant Demo Audio Playback Is Too Fast

### ISSUE THREAD

**Issue by rbrinson** [googlesamples/assistant-sdk-python#84] opened 2017-06-17 05:04 UTC
I have run through the instructions for Getting Started with the Raspberry Pi and Python page for the Google Assistant SDK. My hardware is a Raspberry Pi 3 with an [Audio Injector Sound Card with Microphone HAT](http://www.audioinjector.net/rpi-hat). I have speakers plugged into the 3.5mm headphone jack on the HAT.

In my /boot/config.txt I have the following:
`#dtparam=audio=on`
`dtoverlay=audioinjector-wm8731-audio`
This loads up the HAT sound card as the audio device. So, when I go into alsamixer or Audio Device Settings GUI show the audioinjector-pi-soundcard as the default (and only) sound card.

The instructions for Configure and Test the Audio worked flawlessly. Both `speaker-test` and `arecord` followed by `aplay` work fine producing audio at normal speeds. I am also able to stream music from Google Play Music without any issues I do NOT have a /home/pi/.asoundrc file. When I run `google-assistant-demo`, it starts up fine and responds to the hot words. When I ask Google Assistant a question, it does respond. However, the audio is being played back at a high speed; it sounds like the Chipmunks on steroids. Another observation is that while I have the `google-assistant-demo` running, any audio, such as from `aplay` or the `speaker-test` will also playback at a high speed. When I end the `google-assistant-demo` process, all other audio playback returns to normal speeds.

Any ideas as to what is causing this or how it could be fixed? Thanks!

**Comment by proppy** [comment] 2017-06-19 21:21
@rbrinson do you have the same issue with the gRPC sample `googlesamples-assistant-push-to-talk` ?
https://github.com/googlesamples/assistant-sdk-python/tree/master/google-assistant-sdk/googlesamples/assistant/grpc#run-the-sample

**Comment by rbrinson** [comment] 2017-06-20 17:47
@proppy I do not seem to have the `googlesamples-assistant-push-to-talk` sample. I followed the instructions found at [Download the Library and Run the Sample](https://developers.google.com/assistant/sdk/prototype/getting-started-pi-python/run-sample). How do I get the gRPC samples to try your test? BTW, I wasn't able to even get the google-assistant-demo to run last night. I'm not sure if there was an issue with the oauth server or what, but the errors I was getting had to do with timeouts and server not found. I'm doing some remodeling at the house. So, I had taken down the network and perhaps my pi hole server got confused when things came back up.

**Comment by TheEngler** [comment] 2017-07-26 01:07
@rbrinson I have the same issue with a knockoff HAT.  Did you ever resolve the issue?

**Comment by proppy** [comment] 2017-07-26 04:44
> I do not seem to have the googlesamples-assistant-push-to-talk sample.
@rbrinson if you installed the `google-assistant-sdk` [package](https://pypi.python.org/pypi/google-assistant-sdk) you should have the `googlesamples-assistant-push-to-talk ` installed.

> knockoff HAT
@TheEngler can you point us to the HAT in question?

**Comment by rbrinson** [comment] 2017-07-26 04:47
@TheEngler Sorry, I gave up trying to use the Audio Injector Sound Card HAT. Not only was I getting chipmunk speed audio whenever the Google Assistant Demo was running, I also found that the HAT was generating electromagnetic interference that was wreaking havoc with the WiFi radio, and wireless is a core requirement of my project. So, I switched to using [UGREEN USB Audio Adapter External Stereo Sound Card](https://smile.amazon.com/dp/B016CU2PEU/ref=cm_sw_r_cp_dp_T2_nVbEzbGAMRH7F) and [SunFounder USB 2.0 Mini Microphone](https://smile.amazon.com/dp/B01KLRBHGM/ref=cm_sw_r_cp_dp_T2_lVbEzb5CB0M1G). This combination has worked flawlessly. I turned off the onboard audio jack by commenting out `# dtparam=audio=on` in /boot/config.txt. That made it a little easier in setting up audio playback and my .asoundrc file.

**Comment by TheEngler** [comment] 2017-07-26 11:09
@rbrinson Thanks for the follow up.  I was wondering if I could simply use a USB sound card.  Any reason you didn't use the audio input of the sound card instead of the separate USB mic?

@proppy I purchased one of these HATs:

[https://www.seeedstudio.com/ReSpeaker-2-Mics-Pi-HAT-p-2874.html](url)

and I used their image which already had Google Assistant installed.  I've gotten ZERO assistance from them.

**Comment by rbrinson** [comment] 2017-07-26 16:10
@TheEngler There is no reason why you couldn't use the audio input on the USB sound card that I purchased. However, I did not already have a microphone to plug into that input. So, I HAD to purchase a microphone, and the microphone I mentioned above is the one recommended by the Google Assistant SDK team on the [hardware setup page](https://developers.google.com/assistant/sdk/develop/python/hardware/setup). However, if you already have a microphone to plug into the audio input, then just use that. You can then get your hardware device IDs for your .asoundrc file using `aplay -l` and `arecord -l`. Also, I would recommend just using the latest Raspbian with Pixel image loaded on your SD card and follow the instructions listed on the [Google Assistant SDK page](https://developers.google.com/assistant/sdk/develop/python/) to get the Google Assistant Demo up and running.

**Comment by TheEngler** [comment] 2017-07-26 23:32
@rbrinson Good to know.  Thanks for the follow up.  Wish I would have trusted my gut on going the USB route before wasting the $15 on the knockoff HAT.

**Comment by fazhaa** [comment] 2017-07-27 04:01
@rbrinson Did you resolve this issue? I'm having the same problem with the same HAT and have been unable to find a resolution.

**Comment by TheEngler** [comment] 2017-07-27 11:07
I haven't resolved the issue.  If I do I will post here.  I'm not expecting any assistance from Seeed though.

**Comment by Quas7** [comment] 2017-07-31 19:25
I have the same issue with the seeed 2-mic HAT.
The google-assistant-pushtotalk sample runs just fine. Hotword sample does not - Chipmunk style.
It sounds like it is a 16kHz stream and is getting played at 48kHz for some reason.

**Comment by TheEngler** [comment] 2017-07-31 23:50
@Quas7 - I had already surmised your 48kHZ/16kHz theory but have yet to figure out a solution.  If you find one please post it here for others.

**Comment by MyNameWasUnavailable** [comment] 2017-08-17 00:11
@TheEngler Have you tried building the image from scratch instead of using theirs?  There seems to be mixed reports of this board (I just ordered one and it has yet to arrive) and I'm wondering if it might be an issue in the supplied image

**Comment by TheEngler** [comment] 2017-08-17 00:38
I have not tried building the image from scratch yet.  Been busy the last two weeks and haven't had the opportunity to try things.  Seeed is useless for any help...

**Comment by pradeepprakash** [comment] 2017-08-20 12:30
Hi, 
  Good day. 

Any insights on the below will help. Thanks in advance.

I have got a strange problem with my setup. I got everything setup. All the setup steps recommended by Google is performed successfully. arecord and aplay is successful. Google demo assistant detection working fine - in the sense - that it prints the string after converting sound to text. But when responding, I hear only a crackling sound on the speaker. Also, I see the below errors - clearly ALSA is being starved of data. 
ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {'text': 'what is the weather today'}
ON_RESPONDING_STARTED:
  {'is_error_response': False}
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred                            ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ON_RESPONDING_FINISHED
ON_CONVERSATION_TURN_FINISHED:
  {'with_follow_on_turn': False}

**Comment by TheEngler** [comment] 2017-08-20 18:12
@pradeepprakash Did you apply for (and configure/rename) the:

      client_secret_client-id.json

file for the Google AI?  I am not intimately familiar with the all the nuances but it wouldn't work if you didn't setup in your (free) Google account.  Are you using the same Seeed HAT?  Did you set up your own image or a pre-configured one?  It is difficult to pinpoint the problem without providing others any specifics.

**Comment by pradeepprakash** [comment] 2017-08-21 01:39
@TheEngler - yes, applied for the same. Incorporated the same in pi. I'm fairly confident that it is not a account, privileges issue because - I'm able to trigger the Google assistant, it detects the speech, convert it to a text string. It is during the playback that the ALSA  error is seen and the garbled voice is heard.

I'm running a NOOB + installed Google Python SDK. It's a raspberry pi 3 + USB audio dongle.

Other test files played using aplay, mpg321 or any other tool plays just fine.

Any other suggestions?

**Comment by csprimary** [comment] 2017-08-25 23:24
I am also having the "chipmunk" issue with the seeed respeaker hat. That was using the raspbian image from seeed. I also tried building the image from scratch and was able to get normal speed playback, but the audio was extremely quiet and noisy despite everything I tried in the alsamixer. Installing pulseaudio resulted in Google Assistant no longer picking up input.

**Comment by TheEngler** [comment] 2017-08-27 14:04
ANYONE using the Seeed Studio ReSpeaker 2-Mics Pi HAT please feel free to post here but also add to my post on the SeeedStudio site or start your own question to let them know their product isn't working:

[https://www.seeedstudio.com/ReSpeaker-2-Mics-Pi-HAT-p-2874.html](url)

**Comment by csprimary** [comment] 2017-08-29 00:09
Have done. I would be interested to know what results other people have had setting up the install manually.

**Comment by bobkummerfeld** [comment] 2017-08-29 04:18
I have the same problem (chipmunk output from google-assistant-demo) on rpi3/seeedRespeaker
I killed pulseaudio and checked it didn't restart. Same result - voice decoded ok but result is played at a higher rate (44k vs 16k?).
Audio seems amazingly complicated on linux. Alsa/pulsaudio etc.  I've been scanning all the config files looking for a way to make the default output rate 16k but no luck.

btw the gRPC version (no hotword detection) works fine

**Comment by MyNameWasUnavailable** [comment] 2017-08-29 21:03
I had a chance to have a play yesterday, and I can confirm that in my case, it does not matter if I use the provided image or a roll your own.  The fast playback issue occurs on the hotword version of the sdk.

My suspicion, is that it is a driver related issue, as I tried to install the driver on raspbian stretch, and it didnt work, it said it installed, but just didnt work.  I didnt dig into why, but my suspicion is that it is something with the driver, and maybe how it interacts with the sdk.

If I were a betting man, I'd wager that if (hopefully when) seeed release a new driver to properly support stretch, then the issue may go away...

**Comment by csprimary** [comment] 2017-09-02 11:34
Seeed replied to me on their forum. I don't have time to try this right now, but maybe this will help:

https://www.seeed.cc/topic_detail.html?id=12221

**Comment by Quas7** [comment] 2017-09-02 12:59
they refere to a ale config file - no clue where or what that should be but it sounds promisint.
I referenced this thread there, maybe they will follow up on this.

**Comment by csprimary** [comment] 2017-09-02 18:16
looks like they embedded the image in the middle of the word. ale config file = alexa config file. Are they confusing their virtual assistants?

**Comment by csprimary** [comment] 2017-09-03 16:04
Poster on Seeed FAQ clarified that the file is an alsa config file named asound.conf

I created the file in line with their instructions, but this only resulted in the following error when running Google Assistant

`ON_RESPONDING_STARTED: {'is_error_response': False} ALSA lib pcm.c:7935:(snd_pcm_set_params) Rate doesn't match (requested 48000Hz, get 16000Hz) [1450:1460:ERROR:audio_output_stream.cc(109)] An error occurred when playing audio output ON_RESPONDING_FINISHED ON_CONVERSATION_TURN_FINISHED: {'with_follow_on_turn': False}`

Has anyone else been successful with either of the proposed solutions from Seeed?

**Comment by xiongyihui** [comment] 2017-09-08 07:23
Hi guys, I'm working the issue. It seems:

+ the issue is only related to the hotword sample `google-assistant-demo`. `googlesamples-assistant-push-to-talk` works well.
+ It happened not just on the respeaker 2 mic hat, but also on some USB audio card (from pradeepprakash's comment)

There are two solutions:

1. When using [seeed prebuild image](https://s3-us-west-2.amazonaws.com/wiki.seeed.cc/001share/seeed-raspbian-jessie-20170523.7z) , place [the ALSA configuration file](https://github.com/respeaker/seeed-voicecard/raw/master/asound.conf) to `/etc/asound.conf`
   ```
   wget https://github.com/respeaker/seeed-voicecard/raw/master/asound.conf
   sudo cp asound.conf /etc/asound.conf
   ```
   The alsa configuration uses dmix plugin and dsnoop plugin to support multiple applications to play and record simultaneously.

2. Use pulseaudio. On Raspbian Jessie, pulseaudio will properly detect the voice card. But on Raspbian Stretch, pulseaudio may only detect the voice card as an input device, try the following pulseaudio configuration:

   ```
   wget https://github.com/respeaker/seeed-voicecard/raw/master/default.pa
   sudo cp default.pa /etc/pulse
   ```

When I use the latest Raspbian (2017-08-16) with the respeaker 2 mic hat,  `google-assistant-demo` didn't have the speed issue by default, but the response voice is very low. Using one of the two solutions would solve it.

If you still have the issue after having tried the two solutions,  you can join [the gitter chat room to discuss](https://gitter.im/seeed-voicecard/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

**Comment by csprimary** [comment] 2017-09-10 20:30
Hello xiongyihui,

I tried solution 1. Despite printing an ALSA overrun error to the console, this method worked! Thank you for your help.

**Comment by jrgleason** [comment] 2017-11-10 15:47
I am still getting this, any ideas? I took a clean image from RPi and even tried `wget https://github.com/respeaker/seeed-voicecard/raw/master/asound_2mic.conf` and then renaming it, but I still get

```
(env) pi@raspberrypi:~/code/voice-recognizer-raspi $ python3 src/assistant_library_demo.py
ALSA lib pcm.c:8403:(snd_pcm_set_params) Rate doesn't match (requested 16000Hz, get 48000Hz)
[1215:1253:ERROR:audio_input_processor.cc(755)] Input error
Say "OK, Google" then speak, or press Ctrl+C to quit...
Segmentation fault
```

**Comment by Fleker** [comment] 2017-12-20 18:21
Can you try on the latest version of the SDK?

**Comment by landaisbenj** [comment] 2017-12-31 15:32
Hello. I have rpi3 with latest google sdk install on stretch. I use the 4mic respeaker from seeed. And sound of google are really bad. Not speed but quiet and noisy.
if i test a rec and play like the google sdk guides: 
arecord --format=S16_LE --duration=5 --rate=16000 --file-type=raw out.raw
i've the problem. But if i test this:
arecord --**format=dat** --duration=5 --rate=48000--file-type=raw out.raw
i do not have any problem.

I try this:
2 Use pulseaudio. On Raspbian Jessie, pulseaudio will properly detect the voice card. But on Raspbian Stretch, pulseaudio may only detect the voice card as an input device, try the following pulseaudio configuration:

wget https://github.com/respeaker/seeed-voicecard/raw/master/default.pa
sudo cp default.pa /etc/pulse

like xiongyihui said and now record are less quiet. But noisy too. 


Sorry for my english.

**Comment by Fleker** [comment] 2018-09-15 21:55
Closing this issue. If there are future related issues, please make a new issue. Thanks.

**Closed by Fleker** 2018-09-15 21:55 UTC
Labels: question
